"""Quality gate for LAJ Structural Analyzer against human validated outlines.

This script is diagnostic only. It reads the latest human_laje_outline_validated
events from the LAJ N1 learning store and compares them with the current
slab_elements output generated by the Structural Analyzer/headless run.
It must never be used to feed N3 runtime geometry.
"""

from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path
from typing import Any


PROJECT_DB = Path("D:/Agente-cad-PYSIDE/project_data.vision")
LEARNING_DB = Path("D:/Agente-cad-PYSIDE/engrev_laj_n1_interpretacao_learning.vision")


def _bbox(points: list[list[float]]) -> tuple[float, float, float, float] | None:
    if not points:
        return None
    xs = [float(p[0]) for p in points]
    ys = [float(p[1]) for p in points]
    return min(xs), min(ys), max(xs), max(ys)


def _dims(points: list[list[float]]) -> tuple[float, float, float]:
    box = _bbox(points)
    if not box:
        return 0.0, 0.0, 0.0
    x0, y0, x1, y1 = box
    w = abs(x1 - x0)
    h = abs(y1 - y0)
    area = 0.0
    pts = points[:]
    if pts and pts[0] != pts[-1]:
        pts.append(pts[0])
    for a, b in zip(pts, pts[1:]):
        area += float(a[0]) * float(b[1]) - float(b[0]) * float(a[1])
    return round(max(w, h), 2), round(min(w, h), 2), round(abs(area) / 2.0, 2)


def _latest_human_outlines(labels: set[str] | None = None) -> dict[str, dict[str, Any]]:
    conn = sqlite3.connect(str(LEARNING_DB))
    conn.row_factory = sqlite3.Row
    out: dict[str, dict[str, Any]] = {}
    try:
        rows = conn.execute(
            """
            SELECT e.id, e.created_at, e.elemento_id, f.laje_outline_segs_json
            FROM engrev_laj_n1_interpretacao_events e
            JOIN engrev_laj_n1_interpretacao_features f ON f.event_id=e.id
            WHERE e.event_type='human_laje_outline_validated'
            ORDER BY e.id DESC
            """
        ).fetchall()
    finally:
        conn.close()

    for row in rows:
        raw_id = str(row["elemento_id"] or "").strip().upper()
        digits = "".join(ch for ch in raw_id if ch.isdigit())
        if raw_id.startswith("L"):
            label = raw_id
        elif digits:
            label = f"L{300 + int(digits):03d}"
        else:
            continue
        if labels and label not in labels:
            continue
        if label in out:
            continue
        payload = json.loads(row["laje_outline_segs_json"] or "{}")
        contours = payload.get("contour") if isinstance(payload, dict) else None
        if not contours:
            continue
        points = contours[0].get("points") or []
        comp, larg, area = _dims(points)
        out[label] = {
            "event_id": row["id"],
            "created_at": row["created_at"],
            "points": points,
            "comprimento": comp,
            "largura": larg,
            "area_cm2": area,
            "bbox": _bbox(points),
        }
    return out


def _current_sa_slabs(obra: str, pav: str) -> dict[str, dict[str, Any]]:
    conn = sqlite3.connect(str(PROJECT_DB))
    conn.row_factory = sqlite3.Row
    try:
        project = conn.execute(
            "SELECT id FROM projects WHERE work_name=? AND pavement_name LIKE ?",
            (obra, f"%{pav}%"),
        ).fetchone()
        if not project:
            raise SystemExit(f"Projeto nao encontrado: {obra} pav={pav}")
        rows = conn.execute(
            "SELECT laje_nome, campos_json FROM slab_elements WHERE project_id=? AND classe='LAJ'",
            (project["id"],),
        ).fetchall()
    finally:
        conn.close()
    out = {}
    for row in rows:
        data = json.loads(row["campos_json"] or "{}")
        pts = data.get("coordenadas") or []
        comp, larg, area = _dims(pts)
        out[str(row["laje_nome"]).upper()] = {
            "comprimento": comp,
            "largura": larg,
            "area_cm2": area,
            "bbox": _bbox(pts),
            "method": data.get("method"),
        }
    return out


def _match(sa: dict[str, Any], human: dict[str, Any], tol_dim: float, tol_area: float) -> bool:
    d1 = abs(float(sa["comprimento"]) - float(human["comprimento"]))
    d2 = abs(float(sa["largura"]) - float(human["largura"]))
    dim_ok = d1 <= max(tol_dim, human["comprimento"] * 0.05) and d2 <= max(tol_dim, human["largura"] * 0.05)
    a_ok = abs(float(sa["area_cm2"]) - float(human["area_cm2"])) <= max(tol_area, human["area_cm2"] * 0.06)
    return dim_ok and a_ok


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--obra", default="Obra_TREINO_1")
    parser.add_argument("--pav", default="13")
    parser.add_argument("--labels", default="")
    parser.add_argument("--tol-dim", type=float, default=8.0)
    parser.add_argument("--tol-area", type=float, default=1200.0)
    args = parser.parse_args()

    labels = {x.strip().upper() for x in args.labels.replace(",", " ").split() if x.strip()} or None
    human = _latest_human_outlines(labels)
    current = _current_sa_slabs(args.obra, args.pav)
    rows = []
    ok = 0
    for label in sorted(human):
        sa = current.get(label)
        if not sa:
            rows.append((label, False, None, human[label]))
            continue
        passed = _match(sa, human[label], args.tol_dim, args.tol_area)
        ok += int(passed)
        rows.append((label, passed, sa, human[label]))

    print(f"LAJ Human Quality Gate - {args.obra} pav={args.pav}")
    print(f"Human samples: {len(rows)} | Pass: {ok}/{len(rows)} ({(ok / len(rows) * 100.0) if rows else 0.0:.1f}%)")
    print("Label  Status   SA CxL/Area              Human CxL/Area           Method")
    print("-" * 92)
    for label, passed, sa, hu in rows:
        if sa:
            sa_s = f"{sa['comprimento']:.1f}x{sa['largura']:.1f}/{sa['area_cm2']:.1f}"
            method = sa.get("method") or "-"
        else:
            sa_s = "MISSING"
            method = "-"
        hu_s = f"{hu['comprimento']:.1f}x{hu['largura']:.1f}/{hu['area_cm2']:.1f}"
        print(f"{label:<6} {'OK' if passed else '--':<8} {sa_s:<24} {hu_s:<24} {method}")
    return 0 if ok == len(rows) else 2


if __name__ == "__main__":
    raise SystemExit(main())
